### ISSUE TITLE
Usage of ERCF with flex filament

### ISSUE THREAD

**Issue by michaelbeljaars** [EtteGit/EnragedRabbitProject#105]
Not so much an issue as a question and challenge I guess. I did some investigating online but was not able to find any relevant information on this topic. I have been trying to use the ERCF with flex filament (specifically Ninjatek's Cheeta). Given the appropriate top hat, the filament indeed loads to the extruder, but then prompts an error: 

```
14:19:38
An issue with the ERCF has been detected and the ERCF has been PAUSED
14:19:37
idle_timeout: Timeout set to 72000.00 s
14:19:37
Filament seems blocked between the extruder and the nozzle, calling _ERCF_PAUSE...
```

even though it seems to be properly loaded (I can extrude, and the toolhead sensor is triggered). When ejecting, the filament frequently is not unloaded enough in the extruder and stays stuck between the extruder gears when the ERCF is trying to unload.  Loading ABS and PLA works fine, so I am sure that it is related to the stretch that is inherent in flexible filaments. Anyway, I am curious if others have tried the ERCF with flexible filaments and also if there are steps to take to maybe get it to work.  I know that flexible filaments are difficult to work with loading systems like the ERCF (I also have a Prusa MK3S with MMU2S, which just doesn't allow you to use flexible filaments).

**Comment by EtteGit** [comment]
Hi! Very flex filament should be doable with the ERCF. This error you got is just the result of the flex behavior of the filament impacting some ercf security check.

Just redo the calibration for the final_load_check_threshold that is mentionned at the very end of the manual, using this flex filament, and you should be totally fine =)
