### ISSUE TITLE
Documentation: missing info on rod length for different numbers of filament blocks

### ISSUE THREAD

**Issue by drelich** [EtteGit/EnragedRabbitProject#160]
Going through the documentation, I can see info on how long the wires need to be for a 3, 6 and 9 block version of the ERCF. I cannot find the same kind of info on the length of the rods.

**Comment by olivbd** [comment]
On page 18, you can find typical wire lengths for the selector motor.

![image](https://user-images.githubusercontent.com/11228228/196438741-c3b74942-d513-470d-95f9-cfb117f63eb4.png)

And on the next page, you can find for sensor and encoder wires.

![image](https://user-images.githubusercontent.com/11228228/196439045-cec2d0b0-a949-4c12-97c3-934fb8b2599c.png)

**Comment by drelich** [comment]
Yes, I know, and I acknowledged that. I was asking about the rod lengths, not the wires :) Cheers.

**Comment by olivbd** [comment]
Rod lengths are mentioned in the BOM

https://docs.google.com/spreadsheets/d/1A_qeNeaVprh_iPbvLcLjvJ2o2NfCzjuJam3K3RkWW0w

You have to enter the # number of channels you want and it calculates the lengths for you ;-)

**Comment by drelich** [comment]
Good point. Thanks. BTW: You have to create a copy of that BOM in order to change that number of channels. By default, that BOM opens with View permissions only :)

**Comment by olivbd** [comment]
You're welcome. Yes, you have to create a copy in your own Google Drive storage.

Nevertheless, I agree with you, rods lengths could be mentioned in the documentation. And wires also in the BOM.
