### ISSUE TITLE
 ERCF_HOME does not work (no_toolhead_sensor branch)

### ISSUE THREAD

**Issue by opiswahn** [EtteGit/EnragedRabbitProject#171]
After copying all the relevant config files from the no_toolhead_sensor repo to the right places in klipper i followed the instruction until i was asked to run a  ERCF_HOME. Up to this point everything went smoothly, but the  ERCF_HOME resulted in 
![image](https://user-images.githubusercontent.com/5494461/200787722-b92af00d-3b74-447b-9f4c-8c22b6e13eb4.png)

So what to do here?

**Comment by 0x416E64** [comment]
For me i had to edit path to `ercf_vars.cfg` in the `[save_variables]` section of `ercf_software.cfg`, but i didn't find this step documented anywhere. (I have config in different place than the default `/home/pi/klipper_config/ercf_vars.cfg`)

**Comment by opiswahn** [comment]
@Andior very good point, that did the trick. I also have the `ercf_vars.cfg` located in a sub-directory, and I also have a different username as I am not on a RaspberryPI but on a MKS SKIPR.

That solved it, thx mate!
