### ISSUE TITLE
Is it possible to use ERCF without toolhead sensor?

### ISSUE THREAD

**Issue by Caos-Maker89** [EtteGit/EnragedRabbitProject#190]
Hi, 
I have a sidewinder x1 with klipper.
Is it possible to use ERCF without the toolhead sensor? 

Thank you

**Comment by ningpj** [comment]
Yes, most of us already use sensorless filament homing when loading which progressively advances filament until it hits the extruder gears, stopping when no further movement is detected by the encoder before commencing the hotend load sequence.  Theres also an  option to drop run_current while homing to lessen the impact and risk of grinding filament.

**Comment by Caos-Maker89** [comment]
thank u very much @nigelpjames !
