### ISSUE TITLE
Official CW2 support.

### ISSUE THREAD

**Issue by Zephyrus67** [EtteGit/EnragedRabbitProject#202]
It might just be me not being able to find it but it seems to me there is no "official" mod for the stealthburner cw2 extruder with same sensors are for the afterburner.

Or??

**Comment by dedekcz** [comment]
What about that? :+1: 

https://github.com/EtteGit/EnragedRabbitProject/tree/main/usermods/CW2_with_ECAS_and_optional_sensor
