### ISSUE TITLE
is this based off of SMUff?

### ISSUE THREAD

**Issue by icebal** [EtteGit/EnragedRabbitProject#4]
This project has many similarities to this project:
https://www.thingiverse.com/thing:3431438
Is this coincidence or is EnragedRabbit based on smuff?

**Comment by EtteGit** [comment]
Hello. It's neither a coincidence or based on Smuff directly (i.e. it's not a fork, all was designed from scratch). I took what I consider good ideas from mmu systems (mmu2 and smuff) and added mines, resulting in the enraged rabbit project.

I guess this "issue" can be closed? Lol

**Comment by icebal** [comment]
So its design is based on mmu2 and smuff, but redesigned. since inspiration and design aspects came from other projects, can a small credit be added to reflect that?

**Comment by EtteGit** [comment]
Sure thing

**Comment by icebal** [comment]
Woot thanks!
