### ISSUE TITLE
Dead link to example printer.cfg

### ISSUE THREAD

**Issue by gitbisector** [EtteGit/EnragedRabbitProject#51]
The build guide https://github.com/EtteGit/EnragedRabbitProject/blob/main/Documentation/Build_Guide/Build_guide.md
references a no longer available https://github.com/EtteGit/EnragedRabbitProject/blob/main/Klipper_Macros/printer.cfg

**Comment by EtteGit** [comment]
Hi.
This build guide was nicely done by DustinSpeed back in the ERCF V1.0 days, it is no longer up to date or adapted to the ERCF V1.1. Now everything is in the ERCF manual and FAQ.

I just removed the build guide from the repo, and also closing the ticket.

Thanks for the heads' up anyway =)
