### ISSUE TITLE
Divide by zero error within CALIBRATE_ENCODER

### ISSUE THREAD

**Issue by arron-green** [EtteGit/EnragedRabbitProject#52]
I caused this by forgetting to perform the required `ERCF_SELECT_TOOL TOOL=0` resulting in nothing being measured.  This lead to a fault causing the printer to shutdown.

I understand that this was my fault for not following the manual but this happened to me a couple of times while debugging my encoder resolution.

```
Internal error on command:"ERCF_CALIBRATE_ENCODER"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 182, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 120, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/ercf.py", line 194, in cmd_ERCF_CALIBRATE_ENCODER
    resolution = dist / half_mean
ZeroDivisionError: float division by zero
Transition to shutdown state: Internal error on command:"ERCF_CALIBRATE_ENCODER"
```

Steps to reproduce

```
ECRF_HOME
ERCF_CALIBRATE_ENCODER
```

**Comment by EtteGit** [comment]
Just a heads up to tell you I'll look at that in details soon, sorry for the delay, wish days would be a few hours longer

**Comment by arron-green** [comment]
All good! I'm still looking for examples in klipper on the _preferred_ way to raise exceptions without halting the printer. I'll experiment and we can iterate
