### ISSUE TITLE
Screws for switchwire mounts exist... NO NUTS for said screws can be found

### ISSUE THREAD

**Issue by tnap1979** [EtteGit/EnragedRabbitProject#55]
i can locate the threaded printable screws for the ercf to mount to the frame, but cannot locate the nuts to lock them in place

**Comment by EtteGit** [comment]
The threads are on the parts on the '2020' and '3030' folders (3030 being for the switchwire). There are no nuts.

**Comment by tnap1979** [comment]
Oh jeez... wow.. I'm blind.. haha..
Ok, well in that case.. can close this..
Just built myself a 4port feeder and patch setup..
Dude... your design and setup of this device... blows my mind... are you an engineer of sorts?? Amazing work..  thanks for this project

**Comment by EtteGit** [comment]
:) I'm glad you like it!

**Comment by tnap1979** [comment]
Forgot to ask.. as I'm unsure where to look...
Is there an afterburner motor mount plate that has a heatset insert for the toolhead board that supports the rabbit v3 toolhead board??
![16374455266791883937101603703736](https://user-images.githubusercontent.com/1660801/142742071-69f89d02-4c72-4b48-bb54-5c36e2b8bc92.jpg)

**Comment by EtteGit** [comment]
You'll find what you want here I think https://github.com/VoronDesign/Voron-Hardware/tree/master/Afterburner_Toolhead_PCB/STLs/Clockwork

**Comment by tnap1979** [comment]
I did.. thanks soooo much again..
😀
