### ISSUE TITLE
can anybody give a full example of print end?

### ISSUE THREAD

**Issue by xuanze123qaz** [EtteGit/EnragedRabbitProject#58]
I noticed that there is an "UPDATE_DELAYED_GCODE ID=nevermore_stop_delayed DURATION=900" in ERCF_Manual.pdf. Could anybody help me to find the full example? I can't find the delayed_gcode macro -> "nevermore_stop_delayed" .

**Comment by phil65** [comment]
If you dont have the Nevermore filter (the one installed below the bed) then you dont need to care, just dont include that line. That delayed macro should just make the Nevermore fans stop after 900 seconds since they can be used to cool down the bed.
