### ISSUE TITLE
AH3364Q-P-B Hall Effect sensor (SIP)

### ISSUE THREAD

**Issue by lex007112** [EtteGit/EnragedRabbitProject#61]
Hello, I apologize for my English, because. I use a translator, tell me how you can replace the AH3364Q-P-B Hall Effect sensor (SIP), is there a more common analogue of this hall sensor?

**Comment by lerou114** [comment]
You should probably submit this type of question in discord. There is a channel for Voron Design dedicated to this type of question. Hopefully this helps you out.

**Comment by lex007112** [comment]
> You should probably submit this type of question in discord. There is a channel for Voron Design dedicated to this type of question. Hopefully this helps you out.

Thank you, I will try my luck there too.
