### ISSUE TITLE
Mistakes in the BOM

### ISSUE THREAD

**Issue by vladimir-poleh** [EtteGit/EnragedRabbitProject#65]
Hi,

I have found that BOM contains incorrect quantity for some fasteners.
It should be 28 instead of 26 for the M3 threaded inserts and 22 instead of 20 for the  M3x8 SHCS.

**Comment by mattddonnelly** [comment]
This should all be on the base nominal ERCF:
7x gear box front
4x gear box back
1x gear box motor arm
2x filament block end
3x selector cart
2x drag chain anchor
3x encoder
4x selector motor support
2x drag chain anchor bottom

**Comment by EtteGit** [comment]
I've updated the BOM, sorry for the long delay.
Cheers,
Ette
