### ISSUE TITLE
Manual suggestion for identifying Easy BRD device id

### ISSUE THREAD

**Issue by mattddonnelly** [EtteGit/EnragedRabbitProject#72]
For flashing the Easy BRD  SEEEDUINO, a better method of finding out the exact device would be to use 
ls -l /dev/serial/by-id/

Which should output devices as well as what the device is linked to, e.g. ../../ttyACM0.

This can help identify the seeeduino and also verify it has been flashed successfully.

**Comment by EtteGit** [comment]
I'm closing this as I just updated the manual with this, thanks again =)
