### ISSUE TITLE
ERCF feet dont sit flush on 2020 rail

### ISSUE THREAD

**Issue by Urminme** [EtteGit/EnragedRabbitProject#81]
The mounting holes for the feet on the ERCF are offset so far to the edge when screwing them down on the rails they dip intowards the rails, this throws off the alignment causing things to be very bowed, it seems the way they feet are designed the holes are just way to far towards the edge, the feet need to be leangthed by a few millimeters so the holes will sit in the middle directly about the 2020 rail then when you screw them it they can lay flat on either side of the rail instead of dipping in like they do 
![20220305_211626](https://user-images.githubusercontent.com/97814618/156911546-75cfb13d-e31d-4b57-ade5-7dba6df2340d.jpg)
![20220305_211559](https://user-images.githubusercontent.com/97814618/156911548-ab964b84-d4e8-47da-be2e-ddab761703d8.jpg)

**Comment by EtteGit** [comment]
Hi,
I'm closing this since those were updated 15 days ago (look at the new files in case you want to reprint the feet).
