### ISSUE TITLE
Ptfe tube from hotend cant enter the cw1

### ISSUE THREAD

**Issue by Z3ytrox** [EtteGit/EnragedRabbitProject#85]
The ptfe tube of the hotend cant enter the ercf ab cw1 extruder. Therefor Its pressed against the hole that sometimes lead to failed loads. The filament is sometimes pushed against the ptfe tube instead of inside the ptfe tube. Any fixes for this?

**Comment by Z3ytrox** [comment]
![image](https://user-images.githubusercontent.com/96670295/158244830-44ab463a-1ba3-459c-8d5c-ea41c19470be.png) (Normal AB)
![image](https://user-images.githubusercontent.com/96670295/158244860-1dc1e196-07e7-4cc4-bdff-4ca4277123e4.png)
(ERCF AB)

**Comment by claytono** [comment]
This is called out on page 76 of the manual.  You have to use a shorter PTFE tube.

**Comment by Z3ytrox** [comment]
Yeah ive seen that but how do you solve the issue thats caused by this? The filament thats running into the ptfe instead of through it?
