### ISSUE TITLE
pause between swaps is causing issues with the last update

### ISSUE THREAD

**Issue by arron-green** [EtteGit/EnragedRabbitProject#90]
see discussion here https://discord.com/channels/460117602945990666/909743915475816458/957093117444632618

i was able to get past this issue by increasing the G4 timing defined here https://discord.com/channels/460117602945990666/909743915475816458/957093117444632618

**Comment by EtteGit** [comment]
I've merged your fix yesterday, sorry for the delays and thanks for your contribution !

**Comment by cmroche** [comment]
See PR #102
