### ISSUE TITLE
Error pin P1.0 used multiple times in config

### ISSUE THREAD

**Issue by lex007112** [EtteGit/EnragedRabbitProject#93]
What am I doing wrong? All according to the instructions!!! An error pops up "pin P1.0 used multiple times in config"
![image](https://user-images.githubusercontent.com/57561753/161619637-79122ae4-3adb-4ff7-a46d-52a926f9b35a.png)
![image](https://user-images.githubusercontent.com/57561753/161620128-27d7305f-702b-418e-abde-db22f68fcac7.png)

**Comment by Benoitone** [comment]
check in your other pins settings for P1.0...
Your are using SKR 1.4 board for your ERCF? and the encoder is connect to P1.0?

**Comment by lex007112** [comment]
yes, SKR 1.4, connected correctly

**Comment by Benoitone** [comment]
I think you use have P1.0 somewhere else in your config.
Can you post klippy.log?
