### ISSUE TITLE
pin_override

### ISSUE THREAD

**Issue by Dragi2k** [EtteGit/EnragedRabbitProject#95]
i've noticed a problem that is possible in the klipper config.

The pin_override can only be onced in a config, the second one will be ignored.

On the Documentation should be a part that if somebody noticed that klipper says error pin pa6.. that you should look into your config that pin override is probably in use and the second will be ignored.

**Comment by Anathema-Device** [comment]
There can only be one, the last one read as the config is processed is the one used.  Put all your overrides into one statement.

**Comment by Dragi2k** [comment]
Yea, now i know That too 😂

**Comment by EtteGit** [comment]
Hi, you need to put all the pins you want to duplicate into the same [duplicate_pin_override]. Iirc just list them with coma in-between ;)
