### ISSUE TITLE
Section 'ercf' is not a valid config section

### ISSUE THREAD

**Issue by rwijnhov** [EtteGit/EnragedRabbitProject#99]
I just loaded all the config files for the ercf. But it gives me Section 'ercf' is not a valid config section i am not sure why that is?

**Comment by rwijnhov** [comment]
usererror

**Comment by RcTomcat1** [comment]
And what was the solution? Got the same issue....

**Comment by edgypyro** [comment]
also have this issue

**Comment by Anathema-Device** [comment]
have you correctly installed the ercf.py ?
